### ISSUE TITLE
README

### ISSUE THREAD

**Issue by potato4d** [potato4d/nuxt-firebase-sns-example#1]

**Comment by potato4d** [comment]
![83432c3001afede491bb44c69ef0feaf](https://user-images.githubusercontent.com/6993514/34213748-743d6dec-e5e3-11e7-9b1d-a69a12a5637b.gif)

**Comment by potato4d** [comment]
![screen shot 2017-12-21 at 0 00 22](https://user-images.githubusercontent.com/6993514/34213945-27f5607e-e5e4-11e7-9761-d5e38e8cf209.png)

**Comment by harol-rodriguez** [comment]
How set env?

**Comment by potato4d** [comment]
@harol-rodriguez plz use env vars.
