### ISSUE TITLE
Don't start dev server.. 

### ISSUE THREAD

**Issue by 19park** [potato4d/nuxt-firebase-sns-example#8]
![image](https://user-images.githubusercontent.com/26448546/53467789-00d7df00-3a9b-11e9-9dda-069cf1411f62.png)

:(

node :  v8.15.0
yarm : 1.13.0

**Comment by jay8t6** [comment]
it looks to me like the nuxt config file does not exist in the location. Double check to see if `nuxt.config.js` exists in nuxt-firebase folder

**Comment by potato4d** [comment]
It seems to work on mac. I will validate it in Windows within close range.

<img width="587" alt="screen shot 2019-03-05 at 23 40 03" src="https://user-images.githubusercontent.com/6993514/53813033-099b4a00-3fa0-11e9-9d0d-c74f7faa2917.png">

**Comment by potato4d** [comment]
@19park

**Comment by 19park** [comment]
how use to windows..

**Comment by 19park** [comment]
oh, folder path string in "####" is problem. i solved it.

**Comment by potato4d** [comment]
OK~
